<?php $this->form->prepare(); ?>

<div class="row">
	<div class="col-md-12">
		<p>&nbsp;</p>
	</div>
</div>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="well">
			<?php echo $this->form()->openTag($form); ?>
			<div class="row">
				<div class="col-md-8">
					<h1>Administrator</h1>
					<p>Per accedere, inserisca qui la sua login e password.</p>
				</div>
				<div class="col-md-4"><img src="/img/login.png" alt=""></div>
			</div>
			<hr>

			<?php if ($this->message): ?>
			<div class="alert alert-<?php echo $this->message[0][0]; ?>">
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				<div><?php echo $this->message[0][1]; ?></div>
			</div>
			<?php endif ?>
			
			<div class="form-group">
				<label for="">Indirizzo Email</label>
				<?php echo $this->formRow($form->get('usermail')); ?>
			</div>
			<div class="form-group">
				<label for="">Password</label>
				<?php echo $this->formRow($form->get('pwd')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formElement($form->get('token')); ?>
				<?php echo $this->formElement($form->get('submit')); ?>
			</div>
			<?php echo $this->form()->closeTag(); ?>
		</div>
	</div>
</div>
