<?php echo $this->partial('global/admin-navbar.phtml'); ?>

<div class="row">
	<div class="col-md-12">
		<p>&nbsp;</p>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<p class="lead">Modifica Risorsa Internet</p>
	</div>
	<div class="col-md-6"></div>
</div>

<div class="row">
	<div class="col-md-12">
		<?php echo $this->form()->openTag($form); ?>	
		<div class="form-group">
			<label for="">Titolo dell'articolo</label>
			<?php echo $this->formRow($form->get('fullname')); ?>
		</div>
		<div class="form-group">
			<label for="">URL Slugs</label>
			<div class="input-group">
				<span class="input-group-addon">http://www.php-night.it/link/</span>
				<?php echo $this->formRow($form->get('slug')); ?>
			</div>
		</div>
		<div class="form-group">
			<label for="">Sito internet (comprensivo di http//)</label>
			<?php echo $this->formRow($form->get('website')); ?>
		</div>
		<div class="form-group">
			<label for="">Breve descrizione</label>
			<?php echo $this->formTextarea($form->get('description')); ?>
		</div>
		<div class="form-group">
			<label for="">Tag/parole chiave, separate da una virgola</label>
			<?php echo $this->formRow($form->get('tags')); ?>
		</div>
		<div class="form-group">
			<label for="">Selezionare la categoria</label>
			<?php echo $this->formRow($form->get('category_id')); ?>
		</div>
		<div class="checkbox">
			<label><?php echo $this->formRow($form->get('active')); ?> Mostra sul sito</label>
		</div>
		<div class="form-group">
			<?php echo $this->formElement($form->get('submit')); ?>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>