<div class="row">
	<div class="col-md-12">
		<p>&nbsp;</p>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<h1><small>Administrator - PHP Night</small></h1>
	</div>
	<div class="col-md-6">
		<ul class="list-inline pull-right">
			<li>Bentornato, <strong><?php echo $this->layout()->auth->fullname; ?></strong></li>
			<li><a href="<?php echo $this->url('backoffice/logout'); ?>"><span class="glyphicon glyphicon-off"></span> Logout</a></li>
		</ul>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<ul class="nav nav-tabs">
			<li class="active"><a href="<?php echo $this->url('backoffice/dashboard'); ?>"><span class="glyphicon glyphicon-home"></span> Dashboard</a></li>
			<li><a href="<?php echo $this->url('backoffice/categories'); ?>"><span class="glyphicon glyphicon-list"></span> Categorie</a></li>
			<li><a href="<?php echo $this->url('backoffice/directory'); ?>"><span class="glyphicon glyphicon-briefcase"></span> Risorse Internet</a></li>
		</ul>
	</div>
</div>
