<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Application\Model\CategoriesModel'          => __DIR__ . '//src/Application/Model/CategoriesModel.php',
  'Application\Model\DirectoryModel'           => __DIR__ . '//src/Application/Model/DirectoryModel.php',
  'Application\Factory\DirectoryFactory'       => __DIR__ . '//src/Application/Factory/DirectoryFactory.php',
  'Application\Factory\IndexFactory'           => __DIR__ . '//src/Application/Factory/IndexFactory.php',
  'Application\Controller\DirectoryController' => __DIR__ . '//src/Application/Controller/DirectoryController.php',
  'Application\Controller\IndexController'     => __DIR__ . '//src/Application/Controller/IndexController.php',
  'Application\Module'                         => __DIR__ . '//Module.php',
);
