<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Administrator | PHP Night</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="Concetto Vecchio">
	<link rel="stylesheet" href="/css/bootstrap.min.css">
	<link rel="stylesheet" href="/css/bootstrap-theme.min.css">
	<link rel="stylesheet" href="/css/bootstrap-datatables.css">
	<link rel="stylesheet" href="/css/admin.css">
    <!--[if lt IE 9]>
    <script src="/js/html5shiv.js"></script>
    <script src="/js/respond.min.js"></script>
    <![endif]-->
</head>
<body>

	<div class="container">
		<?php echo $this->content; ?>
	</div>

	<script src="https://code.jquery.com/jquery.js"></script>
	<script src="/js/jquery.dataTables.min.js"></script>
	<script src="/js/bootstrap.min.js"></script>
	<script src="/js/bootstrap-datatables.js"></script>
	<script src="/js/jquery.admin.js"></script>
</body>
</html>