<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Backoffice\Service\ConvertResultSetSQLtoArray' => __DIR__ . '//src/Backoffice/Service/ConvertResultSetSQLtoArray.php',
  'Backoffice\Form\LoginForm'                     => __DIR__ . '//src/Backoffice/Form/LoginForm.php',
  'Backoffice\Form\DirectoryForm'                 => __DIR__ . '//src/Backoffice/Form/DirectoryForm.php',
  'Backoffice\Form\CategoryForm'                  => __DIR__ . '//src/Backoffice/Form/CategoryForm.php',
  'Backoffice\Factory\LoginFactory'               => __DIR__ . '//src/Backoffice/Factory/LoginFactory.php',
  'Backoffice\Factory\DirectoryFactory'           => __DIR__ . '//src/Backoffice/Factory/DirectoryFactory.php',
  'Backoffice\Factory\CategoriesFactory'          => __DIR__ . '//src/Backoffice/Factory/CategoriesFactory.php',
  'Backoffice\Factory\DashboardFactory'           => __DIR__ . '//src/Backoffice/Factory/DashboardFactory.php',
  'Backoffice\Controller\DirectoryController'     => __DIR__ . '//src/Backoffice/Controller/DirectoryController.php',
  'Backoffice\Controller\CategoriesController'    => __DIR__ . '//src/Backoffice/Controller/CategoriesController.php',
  'Backoffice\Controller\LoginController'         => __DIR__ . '//src/Backoffice/Controller/LoginController.php',
  'Backoffice\Controller\DashboardController'     => __DIR__ . '//src/Backoffice/Controller/DashboardController.php',
  'Backoffice\Module'                             => __DIR__ . '//Module.php',
);
